version = 0.1

[default.deploy.parameters]
stack_name = "gmail-assistant-app"
resolve_s3 = true
s3_prefix = "gmail-assistant-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SecretsManagerSecretName=\"gmail/oauth\""
image_repositories = []
